apiVersion: v1
kind: ConfigMap
metadata:
  name: learnx-config
data:
  api_url: "https://api.learnx.example.com"
  s3_endpoint: "https://s3.amazonaws.com"
  s3_bucket: "learnx-production"
  redis_host: "redis-service"
  redis_port: "6379"
