apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: learnx/worker:latest
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: learnx-secrets
              key: database_url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: learnx-secrets
              key: redis_url
        - name: S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: learnx-config
              key: s3_endpoint
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: learnx-secrets
              key: s3_access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: learnx-secrets
              key: s3_secret_key
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: learnx-config
              key: s3_bucket
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: learnx-secrets
              key: openai_api_key
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
