name: Deploy LEARN-X Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd apps/api
          pip install -r requirements.txt
          pip install pytest pytest-cov
          
      - name: Test API with pytest
        run: |
          cd apps/api
          pytest --cov=app tests/
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install frontend dependencies
        run: |
          cd apps/frontend
          npm ci
          
      - name: Run frontend tests
        run: |
          cd apps/frontend
          npm test
  
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/api
          push: true
          tags: learnx/api:latest
      
      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/frontend
          push: true
          tags: learnx/frontend:latest
      
      - name: Build and push AI service image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/ai
          push: true
          tags: learnx/ai:latest
      
      - name: Build and push Worker image
        uses: docker/build-push-action@v4
        with:
          context: ./workers/celery
          push: true
          tags: learnx/worker:latest
  
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name learnx-cluster --region us-west-2
      
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment/api-deployment
          kubectl rollout restart deployment/frontend-deployment
          kubectl rollout restart deployment/ai-deployment
          kubectl rollout restart deployment/worker-deployment
